[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/console/Event/ConsoleExceptionEvent.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/console/Event/ConsoleExceptionEvent.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/console/Event/ConsoleExceptionEvent.php","location":{"uriHash":1304406503,"range":{"start":{"line":0,"character":0},"end":{"line":71,"character":0}}},"children":[{"kind":512,"name":"Symfony\\Component\\Console\\Event","location":{"uriHash":1304406503,"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":42}}}},{"kind":1,"name":"Command","location":{"uriHash":1304406503,"range":{"start":{"line":15,"character":4},"end":{"line":15,"character":45}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Console\\Command\\Command"}]},{"kind":1,"name":"InputInterface","location":{"uriHash":1304406503,"range":{"start":{"line":16,"character":4},"end":{"line":16,"character":50}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Console\\Input\\InputInterface"}]},{"kind":1,"name":"OutputInterface","location":{"uriHash":1304406503,"range":{"start":{"line":17,"character":4},"end":{"line":17,"character":52}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Console\\Output\\OutputInterface"}]},{"kind":1,"name":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent","location":{"uriHash":1304406503,"range":{"start":{"line":26,"character":0},"end":{"line":70,"character":1}}},"children":[{"kind":16,"name":"$exception","location":{"uriHash":1304406503,"range":{"start":{"line":28,"character":12},"end":{"line":28,"character":22}}},"modifiers":4,"scope":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent"},{"kind":16,"name":"$exitCode","location":{"uriHash":1304406503,"range":{"start":{"line":29,"character":12},"end":{"line":29,"character":21}}},"modifiers":4,"scope":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent"},{"kind":32,"name":"__construct","location":{"uriHash":1304406503,"range":{"start":{"line":31,"character":4},"end":{"line":37,"character":5}}},"modifiers":1,"type":"","children":[{"kind":128,"name":"$command","location":{"uriHash":1304406503,"range":{"start":{"line":31,"character":32},"end":{"line":31,"character":48}}},"type":"Symfony\\Component\\Console\\Command\\Command","scope":"__construct"},{"kind":128,"name":"$input","location":{"uriHash":1304406503,"range":{"start":{"line":31,"character":50},"end":{"line":31,"character":71}}},"type":"Symfony\\Component\\Console\\Input\\InputInterface","scope":"__construct"},{"kind":128,"name":"$output","location":{"uriHash":1304406503,"range":{"start":{"line":31,"character":73},"end":{"line":31,"character":96}}},"type":"Symfony\\Component\\Console\\Output\\OutputInterface","scope":"__construct"},{"kind":128,"name":"$exception","location":{"uriHash":1304406503,"range":{"start":{"line":31,"character":98},"end":{"line":31,"character":119}}},"type":"Exception","scope":"__construct"},{"kind":128,"name":"$exitCode","location":{"uriHash":1304406503,"range":{"start":{"line":31,"character":121},"end":{"line":31,"character":130}}},"scope":"__construct"}],"scope":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent"},{"kind":32,"name":"getException","location":{"uriHash":1304406503,"range":{"start":{"line":44,"character":4},"end":{"line":47,"character":5}}},"doc":{"description":"Returns the thrown exception.","type":"Exception"},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent"},{"kind":32,"name":"setException","location":{"uriHash":1304406503,"range":{"start":{"line":56,"character":4},"end":{"line":59,"character":5}}},"doc":{"description":"Replaces the thrown exception.\n\nThis exception will be thrown if no response is set in the event.","type":""},"modifiers":1,"type":"","children":[{"kind":128,"name":"$exception","location":{"uriHash":1304406503,"range":{"start":{"line":56,"character":33},"end":{"line":56,"character":54}}},"type":"Exception","doc":{"description":"The thrown exception","type":"Exception"},"scope":"setException"}],"scope":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent"},{"kind":32,"name":"getExitCode","location":{"uriHash":1304406503,"range":{"start":{"line":66,"character":4},"end":{"line":69,"character":5}}},"doc":{"description":"Gets the exit code.","type":"int"},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\Console\\Event\\ConsoleExceptionEvent"}],"associated":[{"kind":1,"name":"Symfony\\Component\\Console\\Event\\ConsoleEvent"}],"doc":{"description":"Allows to handle exception thrown in a command.","type":""},"modifiers":0}]},"_hash":1304406503}]]