[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/http-kernel/Exception/ServiceUnavailableHttpException.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/http-kernel/Exception/ServiceUnavailableHttpException.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/http-kernel/Exception/ServiceUnavailableHttpException.php","location":{"uriHash":1360628785,"range":{"start":{"line":0,"character":0},"end":{"line":34,"character":0}}},"children":[{"kind":512,"name":"Symfony\\Component\\HttpKernel\\Exception","location":{"uriHash":1360628785,"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":49}}}},{"kind":1,"name":"Symfony\\Component\\HttpKernel\\Exception\\ServiceUnavailableHttpException","location":{"uriHash":1360628785,"range":{"start":{"line":16,"character":0},"end":{"line":33,"character":1}}},"children":[{"kind":32,"name":"__construct","location":{"uriHash":1360628785,"range":{"start":{"line":24,"character":4},"end":{"line":32,"character":5}}},"doc":{"description":"","type":""},"modifiers":1,"type":"","children":[{"kind":128,"name":"$retryAfter","location":{"uriHash":1360628785,"range":{"start":{"line":24,"character":32},"end":{"line":24,"character":50}}},"doc":{"description":"The number of seconds or HTTP-date after which the request may be retried","type":"int|string"},"value":"null","scope":"__construct"},{"kind":128,"name":"$message","location":{"uriHash":1360628785,"range":{"start":{"line":24,"character":52},"end":{"line":24,"character":67}}},"doc":{"description":"The internal exception message","type":"string"},"value":"null","scope":"__construct"},{"kind":128,"name":"$previous","location":{"uriHash":1360628785,"range":{"start":{"line":24,"character":69},"end":{"line":24,"character":96}}},"type":"Exception","doc":{"description":"The previous exception","type":"Exception"},"value":"null","scope":"__construct"},{"kind":128,"name":"$code","location":{"uriHash":1360628785,"range":{"start":{"line":24,"character":98},"end":{"line":24,"character":107}}},"doc":{"description":"The internal exception code","type":"int"},"value":"0","scope":"__construct"}],"scope":"Symfony\\Component\\HttpKernel\\Exception\\ServiceUnavailableHttpException"}],"associated":[{"kind":1,"name":"Symfony\\Component\\HttpKernel\\Exception\\HttpException"}],"modifiers":0}]},"_hash":1360628785}]]